"""Added new columns email and grade 

Revision ID: ccca81cd426b
Revises: 84b1e7bed0fc
Create Date: 2023-09-06 19:11:54.024193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccca81cd426b'
down_revision: Union[str, None] = '84b1e7bed0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('enrolledDate', sa.DateTime(), nullable=True))
    op.create_unique_constraint('unique_email', 'students', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email', 'students', type_='unique')
    op.drop_column('students', 'enrolledDate')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
